"""add fuel price history

Revision ID: 53548fd46c68
Revises: 5459138b7c6e
Create Date: 2026-08-17 09:19:57.231687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53548fd46c68'
down_revision: Union[str, Sequence[str], None] = '5459138b7c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_price_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fuel_id', sa.String(length=36), nullable=False),
    sa.Column('old_rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_by_id', sa.String(length=36), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_price_history_changed_by_id'), ['changed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_price_history_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_price_history_fuel_id'), ['fuel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_price_history_fuel_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_price_history_effective_from'))
        batch_op.drop_index(batch_op.f('ix_fuel_price_history_changed_by_id'))

    op.drop_table('fuel_price_history')
    # ### end Alembic commands ###
