"""add_shift_reconciliation_table

Revision ID: 5459138b7c6e
Revises: 418d6c03bdf4
Create Date: 2026-08-16 20:01:42.731591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5459138b7c6e'
down_revision: Union[str, Sequence[str], None] = '418d6c03bdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_reconciliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('declared_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_variance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_upi', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('declared_upi', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('upi_variance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_card', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('declared_card', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('card_variance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('performed_by_id', sa.String(length=36), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_reconciliations_shift_id'), ['shift_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_reconciliations_shift_id'))

    op.drop_table('shift_reconciliations')
    # ### end Alembic commands ###
