"""add_payments_table

Revision ID: d948d120d0c7
Revises: 211e22a49e32
Create Date: 2026-08-16 19:11:09.704318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd948d120d0c7'
down_revision: Union[str, Sequence[str], None] = '211e22a49e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('reference_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payment_at', sa.DateTime(), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('attendant_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attendant_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_payment_at'), ['payment_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_sale_id'), ['sale_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_sale_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_at'))

    op.drop_table('payments')
    # ### end Alembic commands ###
