"""add check constraints for value invariants

Revision ID: fa88f5c33f4c
Revises: 53548fd46c68
Create Date: 2026-08-17 12:33:11.220717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa88f5c33f4c'
down_revision: Union[str, Sequence[str], None] = '53548fd46c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_accounts', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_credit_accounts_due_days_non_negative', 'payment_due_days >= 0')
        batch_op.create_check_constraint('ck_credit_accounts_limit_non_negative', 'credit_limit >= 0')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_expenses_amount_positive', 'amount > 0')

    with op.batch_alter_table('fuel_price_history', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_fuel_price_history_new_rate_positive', 'new_rate_per_liter > 0')

    with op.batch_alter_table('fuels', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_fuels_rate_non_negative', 'rate_per_liter >= 0')

    with op.batch_alter_table('nozzle_assignments', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_nozzle_assignments_closing_not_before_opening', 'closing_meter IS NULL OR closing_meter >= opening_meter')
        batch_op.create_check_constraint('ck_nozzle_assignments_opening_meter_non_negative', 'opening_meter >= 0')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_payments_amount_non_negative', 'amount >= 0')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_sales_amount_non_negative', 'amount >= 0')
        batch_op.create_check_constraint('ck_sales_quantity_positive', 'quantity > 0')
        batch_op.create_check_constraint('ck_sales_rate_non_negative', 'rate_per_liter >= 0')

    with op.batch_alter_table('tank_transactions', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_tank_transactions_quantity_non_zero', 'quantity != 0')

    with op.batch_alter_table('tanks', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_tanks_capacity_positive', 'capacity > 0')
        batch_op.create_check_constraint('ck_tanks_stock_non_negative', 'current_stock >= 0')
        batch_op.create_check_constraint('ck_tanks_stock_within_capacity', 'current_stock <= capacity')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tanks', schema=None) as batch_op:
        batch_op.drop_constraint('ck_tanks_stock_within_capacity', type_='check')
        batch_op.drop_constraint('ck_tanks_stock_non_negative', type_='check')
        batch_op.drop_constraint('ck_tanks_capacity_positive', type_='check')

    with op.batch_alter_table('tank_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('ck_tank_transactions_quantity_non_zero', type_='check')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('ck_sales_rate_non_negative', type_='check')
        batch_op.drop_constraint('ck_sales_quantity_positive', type_='check')
        batch_op.drop_constraint('ck_sales_amount_non_negative', type_='check')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('ck_payments_amount_non_negative', type_='check')

    with op.batch_alter_table('nozzle_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('ck_nozzle_assignments_opening_meter_non_negative', type_='check')
        batch_op.drop_constraint('ck_nozzle_assignments_closing_not_before_opening', type_='check')

    with op.batch_alter_table('fuels', schema=None) as batch_op:
        batch_op.drop_constraint('ck_fuels_rate_non_negative', type_='check')

    with op.batch_alter_table('fuel_price_history', schema=None) as batch_op:
        batch_op.drop_constraint('ck_fuel_price_history_new_rate_positive', type_='check')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('ck_expenses_amount_positive', type_='check')

    with op.batch_alter_table('credit_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('ck_credit_accounts_limit_non_negative', type_='check')
        batch_op.drop_constraint('ck_credit_accounts_due_days_non_negative', type_='check')

    # ### end Alembic commands ###
