"""add audit log hash chain

Revision ID: 52bf0b01839b
Revises: d4475c941f23
Create Date: 2026-08-17 17:51:53.451971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bf0b01839b'
down_revision: Union[str, Sequence[str], None] = 'd4475c941f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('entry_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_entry_hash'), ['entry_hash'], unique=False)

    # ### end Alembic commands ###

    # Triggers make the append-only rule real rather than a convention.
    # Nothing in the application updates or deletes an audit row, but the
    # .db file sits on a forecourt PC and anyone with a DB browser could
    # rewrite the trail. These reject the statement outright, so even
    # direct SQL against the file fails.
    #
    # This is the tamper-RESISTANT layer; the hash chain added above is the
    # tamper-EVIDENT one. Both are needed: triggers can be dropped by
    # anyone who can also run DDL, and the chain is what detects it if they
    # do.
    op.execute("""
        CREATE TRIGGER audit_logs_no_update
        BEFORE UPDATE ON audit_logs
        BEGIN
            SELECT RAISE(ABORT, 'audit_logs is append-only; entries cannot be modified');
        END;
    """)
    op.execute("""
        CREATE TRIGGER audit_logs_no_delete
        BEFORE DELETE ON audit_logs
        BEGIN
            SELECT RAISE(ABORT, 'audit_logs is append-only; entries cannot be deleted');
        END;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_logs_no_update")
    op.execute("DROP TRIGGER IF EXISTS audit_logs_no_delete")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entry_hash'))
        batch_op.drop_column('entry_hash')
        batch_op.drop_column('previous_hash')

    # ### end Alembic commands ###
