"""add tank_id to nozzles

Revision ID: 43e132453c80
Revises: be4e2b8f1220
Create Date: 2026-08-16 17:23:43.816132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e132453c80'
down_revision: Union[str, Sequence[str], None] = 'be4e2b8f1220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nozzles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tank_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_nozzles_tank_id_tanks', 'tanks', ['tank_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nozzles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_nozzles_tank_id_tanks', type_='foreignkey')
        batch_op.drop_column('tank_id')

    # ### end Alembic commands ###
