"""add locked_at to users

Revision ID: d4475c941f23
Revises: fa88f5c33f4c
Create Date: 2026-08-17 17:47:02.609784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# UtcDateTime is a custom TypeDecorator, so Alembic renders it by its
# fully-qualified name but does not add the import itself.
import app.database.types


# revision identifiers, used by Alembic.
revision: str = 'd4475c941f23'
down_revision: Union[str, Sequence[str], None] = 'fa88f5c33f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_at', app.database.types.UtcDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_at')

    # ### end Alembic commands ###
