"""baseline schema

Revision ID: dacfb10de7de
Revises: 
Create Date: 2026-08-16 00:21:21.185968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacfb10de7de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispensers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispensers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispensers_code'), ['code'], unique=True)

    op.create_table('fuels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fuel_type', sa.String(length=128), nullable=False),
    sa.Column('rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuels_fuel_type'), ['fuel_type'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('nozzles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('dispenser_id', sa.String(length=36), nullable=False),
    sa.Column('fuel_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dispenser_id'], ['dispensers.id'], ),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nozzles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nozzles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_nozzles_dispenser_id'), ['dispenser_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('tanks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('fuel_id', sa.String(length=36), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('opening_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('calibration_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tanks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tanks_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('device_info', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('contact_number', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('designation', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('assigned_outlet', sa.String(length=128), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=128), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=True)

    op.create_table('fuel_reconciliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tank_id', sa.String(length=36), nullable=False),
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('opening_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('sold_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('expected_closing_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('physical_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('variance', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('variance_percent', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('performed_by_id', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_reconciliations_reconciliation_date'), ['reconciliation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_reconciliations_tank_id'), ['tank_id'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_label', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('opened_by_id', sa.String(length=36), nullable=False),
    sa.Column('closed_by_id', sa.String(length=36), nullable=True),
    sa.Column('supervisor_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('reopened_by_id', sa.String(length=36), nullable=True),
    sa.Column('reopened_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reopened_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_date', 'shift_label', name='uq_shift_date_label')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_shift_date'), ['shift_date'], unique=False)

    op.create_table('tank_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tank_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_at', sa.DateTime(), nullable=False),
    sa.Column('reference', sa.String(length=256), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tank_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tank_transactions_tank_id'), ['tank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tank_transactions_transaction_at'), ['transaction_at'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('device_info', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('shift_label', sa.String(length=64), nullable=True),
    sa.Column('supervisor_id', sa.String(length=36), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('correction_reason', sa.String(length=512), nullable=True),
    sa.Column('corrected_by_id', sa.String(length=36), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['corrected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_employee_date')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_employee_id'), ['employee_id'], unique=False)

    op.create_table('employee_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('file_reference', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_documents_employee_id'), ['employee_id'], unique=False)

    op.create_table('nozzle_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('nozzle_id', sa.String(length=36), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('opening_meter', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('closing_meter', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('assigned_by_id', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['nozzle_id'], ['nozzles.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nozzle_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nozzle_assignments_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nozzle_assignments_nozzle_id'), ['nozzle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nozzle_assignments_shift_id'), ['shift_id'], unique=False)

    op.create_table('tank_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tank_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=True),
    sa.Column('reading_at', sa.DateTime(), nullable=False),
    sa.Column('dip_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('physical_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tank_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tank_readings_reading_at'), ['reading_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tank_readings_tank_id'), ['tank_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tank_readings_tank_id'))
        batch_op.drop_index(batch_op.f('ix_tank_readings_reading_at'))

    op.drop_table('tank_readings')
    with op.batch_alter_table('nozzle_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nozzle_assignments_shift_id'))
        batch_op.drop_index(batch_op.f('ix_nozzle_assignments_nozzle_id'))
        batch_op.drop_index(batch_op.f('ix_nozzle_assignments_employee_id'))

    op.drop_table('nozzle_assignments')
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_documents_employee_id'))

    op.drop_table('employee_documents')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_attendance_date'))

    op.drop_table('attendance')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('tank_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tank_transactions_transaction_at'))
        batch_op.drop_index(batch_op.f('ix_tank_transactions_tank_id'))

    op.drop_table('tank_transactions')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_shift_date'))

    op.drop_table('shifts')
    with op.batch_alter_table('fuel_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_reconciliations_tank_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_reconciliations_reconciliation_date'))

    op.drop_table('fuel_reconciliations')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))

    op.drop_table('employees')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tanks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tanks_code'))

    op.drop_table('tanks')
    op.drop_table('role_permissions')
    with op.batch_alter_table('nozzles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nozzles_dispenser_id'))
        batch_op.drop_index(batch_op.f('ix_nozzles_code'))

    op.drop_table('nozzles')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))

    op.drop_table('permissions')
    with op.batch_alter_table('fuels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuels_fuel_type'))

    op.drop_table('fuels')
    with op.batch_alter_table('dispensers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispensers_code'))

    op.drop_table('dispensers')
    # ### end Alembic commands ###
