"""add customers and sales

Revision ID: 211e22a49e32
Revises: 43e132453c80
Create Date: 2026-08-16 17:30:12.628660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211e22a49e32'
down_revision: Union[str, Sequence[str], None] = '43e132453c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_number', sa.String(length=32), nullable=False),
    sa.Column('sale_at', sa.DateTime(), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('nozzle_id', sa.String(length=36), nullable=False),
    sa.Column('fuel_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('tank_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('reversal_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuels.id'], ),
    sa.ForeignKeyConstraint(['nozzle_id'], ['nozzles.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversal_transaction_id'], ['tank_transactions.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['tank_transaction_id'], ['tank_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_nozzle_id'), ['nozzle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_receipt_number'), ['receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_sale_at'), ['sale_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_shift_id'), ['shift_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_shift_id'))
        batch_op.drop_index(batch_op.f('ix_sales_sale_at'))
        batch_op.drop_index(batch_op.f('ix_sales_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_sales_nozzle_id'))

    op.drop_table('sales')
    op.drop_table('customers')
    # ### end Alembic commands ###
