"""add procurement tables

Revision ID: be4e2b8f1220
Revises: 8410ceaed0bf
Create Date: 2026-08-16 13:51:29.500363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4e2b8f1220'
down_revision: Union[str, Sequence[str], None] = '8410ceaed0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_person', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('gst_number', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_number'), ['po_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('fuel_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuels.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('supplier_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_invoices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('fuel_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('tank_id', sa.String(length=36), nullable=False),
    sa.Column('received_by_employee_id', sa.String(length=36), nullable=False),
    sa.Column('tanker_number', sa.String(length=32), nullable=False),
    sa.Column('driver_name', sa.String(length=128), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('document_verified_by_id', sa.String(length=36), nullable=True),
    sa.Column('document_verified_at', sa.DateTime(), nullable=True),
    sa.Column('quality_verified_by_id', sa.String(length=36), nullable=True),
    sa.Column('quality_verified_at', sa.DateTime(), nullable=True),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('pre_dip_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('pre_dip_reading_id', sa.String(length=36), nullable=True),
    sa.Column('post_dip_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('post_dip_reading_id', sa.String(length=36), nullable=True),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('tank_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_verified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_dip_reading_id'], ['tank_readings.id'], ),
    sa.ForeignKeyConstraint(['pre_dip_reading_id'], ['tank_readings.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['quality_verified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['received_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.ForeignKeyConstraint(['tank_transaction_id'], ['tank_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_deliveries_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_deliveries_tank_id'), ['tank_id'], unique=False)

    op.create_table('supplier_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_invoice_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_invoice_id'], ['supplier_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_payments_supplier_invoice_id'), ['supplier_invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_payments_supplier_invoice_id'))

    op.drop_table('supplier_payments')
    with op.batch_alter_table('fuel_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_deliveries_tank_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_deliveries_purchase_order_id'))

    op.drop_table('fuel_deliveries')
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_supplier_id'))

    op.drop_table('supplier_invoices')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_purchase_order_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_number'))

    op.drop_table('purchase_orders')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
