"""add must_change_password to users

Revision ID: 8410ceaed0bf
Revises: dacfb10de7de
Create Date: 2026-08-16 00:30:30.781862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8410ceaed0bf'
down_revision: Union[str, Sequence[str], None] = 'dacfb10de7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    server_default=false() so this is safe to add to a table that
    already has rows in it - existing users are not retroactively
    forced to change their password, only newly created or
    admin-password-reset accounts are (see UserService.create_user /
    reset_password).
    """
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
