"""add app settings table

Revision ID: d6e5393626bf
Revises: 52bf0b01839b
Create Date: 2026-08-17 19:42:18.977217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.database.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'd6e5393626bf'
down_revision: Union[str, Sequence[str], None] = '52bf0b01839b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('gst_number', sa.String(length=32), nullable=True),
    sa.Column('licence_number', sa.String(length=64), nullable=True),
    sa.Column('receipt_footer', sa.Text(), nullable=True),
    sa.Column('offsite_backup_dir', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.database.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.database.types.UtcDateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
