import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, Date, DateTime, ForeignKey, Numeric, String, Text
from sqlalchemy.orm import relationship
from app.database.types import UtcDateTime

from .base import Base


class SupplierInvoice(Base):
    """A supplier's invoice for a delivery (problemstatement.md #12: step
    10, Invoice). invoice_number is the supplier's own numbering, not
    generated by this app. status tracks payment progress and is derived
    from the sum of its SupplierPayments, never set directly."""

    __tablename__ = "supplier_invoices"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    invoice_number = Column(String(64), nullable=False)
    supplier_id = Column(String(36), ForeignKey("suppliers.id"), nullable=False, index=True)
    purchase_order_id = Column(String(36), ForeignKey("purchase_orders.id"), nullable=True)

    invoice_date = Column(Date, nullable=False)
    due_date = Column(Date, nullable=True)
    amount = Column(Numeric(12, 2), nullable=False)
    status = Column(String(32), nullable=False)

    recorded_by_id = Column(String(36), ForeignKey("users.id"), nullable=False)
    remarks = Column(Text, nullable=True)

    created_at = Column(UtcDateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    supplier = relationship("Supplier")
    purchase_order = relationship("PurchaseOrder")
    recorded_by = relationship("User")
    payments = relationship("SupplierPayment", back_populates="invoice")

    def __repr__(self) -> str:
        return f"<SupplierInvoice(invoice_number={self.invoice_number!r}, status={self.status!r})>"


class SupplierPayment(Base):
    """A payment made against a SupplierInvoice (problemstatement.md #12:
    step 11, Supplier Payment). Never edited/deleted once recorded - a
    correction is a new record, not a change to history."""

    __tablename__ = "supplier_payments"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    supplier_invoice_id = Column(String(36), ForeignKey("supplier_invoices.id"), nullable=False, index=True)

    amount = Column(Numeric(12, 2), nullable=False)
    payment_date = Column(Date, nullable=False)
    payment_method = Column(String(32), nullable=False)
    reference = Column(String(128), nullable=True)

    recorded_by_id = Column(String(36), ForeignKey("users.id"), nullable=False)
    remarks = Column(Text, nullable=True)

    created_at = Column(UtcDateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    invoice = relationship("SupplierInvoice", back_populates="payments")
    recorded_by = relationship("User")

    def __repr__(self) -> str:
        return f"<SupplierPayment(supplier_invoice_id={self.supplier_invoice_id!r}, amount={self.amount!r})>"
